### ISSUE TITLE
High CPU usage when displaying static PNGs in the viewport

### ISSUE THREAD

**Issue by in1tiate** [AttorneyOnline/AO2-Client#128]
Noticed this while idling. CPU usage when displaying GIF characters was [0.2%](https://i.imgur.com/MIOthQu.png) at peak, but when displaying static PNG characters usage jumps to around [28.5%](https://i.imgur.com/cDqR0bY.png) or higher. Issue is present in the last compiling commit at the time of writing.

**Comment by oldmud0** [comment]
Thought this was fixed somewhere already.

That's because static PNGs are being treated as one-frame animated PNGs and therefore go through the animated PNG machinery. It's probably flushing and reloading the same frame at a delay of 0.

**Comment by in1tiate** [comment]
Appears I spoke too soon - this issue is still present, though now the cause seems to be more elusive. I can't get it to consistently happen, but it eventually will.

**Comment by in1tiate** [comment]
...or not. Having qDebug log the frame number reveals that the bug is in fact triggering even when the frame count is zero. I'm thinking the bug may lie elsewhere in the viewport machinery.

**Comment by in1tiate** [comment]
Oh, epic. The movie_ticker function also calls `ticker->start(m_movie->nextFrameDelay())` and has been thusly bypassing my check altogether. Fun. Adding another check seems to fix it.
