### ISSUE TITLE
Text in IC log disappears when using <hahaha> 

### ISSUE THREAD

**Issue by Crystalwarrior** [AttorneyOnline/AO2-Client#221]
![pictured](https://user-images.githubusercontent.com/3470436/89101084-a49e8a80-d405-11ea-804c-26a77c24d3a2.png)
![pictured2](https://user-images.githubusercontent.com/3470436/89101088-aec08900-d405-11ea-9039-c731863968da.png)
Does not happen on my end, only one user has reported this issue so far. Log goes downwards/upwards does not seem to affect this.

**Comment by GeckBluntBlade** [comment]
Problem's likely origin is from the 17th (KFO update 4 related?). Didn't seem to have this problem on the 16th when I was recording.

**Comment by Crystalwarrior** [comment]
17th of August @GeckBluntBlade?

**Comment by oldmud0** [comment]
Was this fixed in be4b6e78ab74a1f5fded5e855c8847c844bfe850?

**Comment by Crystalwarrior** [comment]
@oldmud0 I believe this was discovered on the Release Day version of AO2, unless it updated since then it should be still present I think,

**Comment by oldmud0** [comment]
oh this is specifically for the ic log

**Comment by scatterflower** [comment]
Could not reproduce

**Comment by Crystalwarrior** [comment]
Reopening because of a breakthrough in investigation: this only seems to happen when log_goes_downwards tick is OFF. Might be an issue associated with the shitty way IC logs are written aka duplicate code.

**Comment by scatterflower** [comment]
Turns out this was actually caused by disabling colors in IC log
